# Generated by Django 3.2.7 on 2021-09-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0002_rename_homefinderuser_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
