# Generated by Django 3.2.7 on 2021-09-24 16:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0004_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
