# Generated by Django 3.2.4 on 2021-09-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0005_alter_account_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
    ]
