# Generated by Django 3.2.7 on 2021-10-06 14:18

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0006_alter_account_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('location', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('property_type', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('status', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('carea', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('barea', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('beds', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('parking', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('property_des', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('imagefile', models.FileField(blank=True, null=True, upload_to='Images/%Y/%m/%d/')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='Videos/%Y/%m/%d/')),
                ('name', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('phone_no', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('mobile_no', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('email', models.EmailField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('skype', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('owner_des', models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('owner_imagefile', models.FileField(blank=True, null=True, upload_to='ProfileImages/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
