# Generated by Django 3.2.7 on 2021-10-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0011_auto_20211010_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
