# Generated by Django 3.2.7 on 2021-10-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0014_auto_20211013_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
