# Generated by Django 3.2.7 on 2021-10-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0015_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagefile',
            field=models.FileField(blank=True, null=True, upload_to='Images'),
        ),
    ]
