# Generated by Django 3.2.7 on 2021-10-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0018_auto_20211017_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyImages',
        ),
    ]
