# Generated by Django 3.2.7 on 2021-10-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0019_delete_propertyimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='barea',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='carea',
            new_name='price',
        ),
    ]
