# Generated by Django 3.2.7 on 2021-10-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0020_auto_20211017_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='post',
            name='skype',
        ),
    ]
