# Generated by Django 3.2.7 on 2021-10-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0021_auto_20211018_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
