# Generated by Django 3.2.7 on 2021-10-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0023_auto_20211021_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_status_by', models.CharField(max_length=225, null=True)),
            ],
        ),
    ]
