# Generated by Django 3.2.7 on 2021-10-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0024_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
