# Generated by Django 3.2.7 on 2021-10-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0025_delete_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
