# Generated by Django 3.2.7 on 2021-11-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0026_auto_20211022_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagefile',
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefile', models.FileField(blank=True, null=True, upload_to='Images')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeFinderApp.post')),
            ],
            options={
                'db_table': 'PostImages',
            },
        ),
    ]
