# Generated by Django 3.2.7 on 2021-11-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFinderApp', '0027_auto_20211109_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagefile',
            field=models.FileField(blank=True, null=True, upload_to='Images'),
        ),
    ]
